[www]
user = nobody
group = nobody

; Ecouter sur le port 9000 (0.0.0.0:port)
listen = 0.0.0.0:9000

listen.owner = nobody
listen.group = nobody

; Ne pas vider les variables d'environnement (pour SQL_DATABASE, SQL_USER, etc.)
clear_env = no

pm = dynamic
pm.max_children = 5
pm.start_servers = 2
pm.min_spare_servers = 1
pm.max_spare_servers = 3